# Site
name: 'Eastbourne Music Review'
description: 'Local talent, venues and audiences'
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
email: 'contact@eastbournemusicreview.com'
# mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           "Analog Man"
      # site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            "A pedal-powered luddite that's more into tubes than profilers."
      # email:          wowthemesnet@gmail.com
      # twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           "Wally's ghost"
      avatar:         /assets/images/avatar2.jpg
      bio:            "Writer"
      # email:          fakemail@gmail.com
      # twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]